# config.py

# --- API Keys and Secrets ---

# Paste your VirusTotal API key here
VT_API_KEY = "PASTE_YOUR_VT_KEY_HERE"

SHODAN_API_KEY = "PASTE_YOUR_SHODAN_KEY_HERE"
URLSCAN_API_KEY = "PASTE_YOUR_URLSCAN_KEY_HERE"
GOOGLE_API_KEY = "PASTE_YOUR_GOOGLE_KEY_HERE"
OTX_API_KEY = "PASTE_YOUR_OTX_KEY_HERE"
ABUSEIPDB_API_KEY = "PASTE_YOUR_ABUSEIPDB_KEY_HERE"

# We can add other keys here in the future
# HIBP_API_KEY = "PASTE_YOUR_HIBP_KEY_HERE"