# config.py.example

# --- API Keys and Secrets ---
# INSTRUCTIONS: Copy this file to config.py and add your secret API keys.

VT_API_KEY = "PASTE_YOUR_VIRUSTOTAL_API_KEY_HERE"
SHODAN_API_KEY = "PASTE_YOUR_SHODAN_API_KEY_HERE"
URLSCAN_API_KEY = "PASTE_YOUR_URLSCAN_API_KEY_HERE"
GOOGLE_API_KEY = "PASTE_YOUR_GOOGLE_API_KEY_HERE"
OTX_API_KEY = "PASTE_YOUR_OTX_API_KEY_HERE"
